### ISSUE TITLE
Input geogfn is never set

### ISSUE THREAD

**Issue by mbutler808** [nmatzke/BioGeoBEARS#10]
https://github.com/nmatzke/BioGeoBEARS/blob/b44aa11a7f0e44599a3cd4d2824cac9462c63c26/R/BioGeoBEARS_classes_v1.R#L1769-L1770

Hi folks, thanks for this great package. In the run object constructor `define_BioGeoBEARS_run()`, there is an argument for the georange information, `geogfn`, but it does not appear anywhere in the function. And indeed objects created with this function are lacking this slot, even if something is specified. 
Can you add it to the input list? 

Otherwise, an object constructed with this call is broken:

```
trfn = "../../data/trees/biogeo.tree"
geogfn = "../../data/geobins/geobins.txt"

x = define_BioGeoBEARS_run(
  	trfn=trfn, 
  	geogfn=geogfn, 
  	max_range_size = 2,
    min_branchlength = 0.000001,
  	include_null_range = TRUE,
  	num_cores_to_use = 4,
  	force_sparse = FALSE
  )
```

The only way to get this to work is to hand-add it after constructing the object:
```
  x$geogfn <- geogfn
```

I think all you have to do is add:
```
inputs$geogfn = geogfn 
```
Thanks,
Marguerite

**Comment by nmatzke** [comment]
Thanks!  I have made this change. & committed.  Cheers! Nick
