### ISSUE TITLE
plot_BioGeoBEARS_results states are cutoff with very low statecex values

### ISSUE THREAD

**Issue by natis1** [nmatzke/BioGeoBEARS#2]
![example image](https://user-images.githubusercontent.com/2016651/63531764-72cb3700-c4c6-11e9-82d6-0f87372053de.png)

I'm trying to plot a very large tree which requires very small statecex values and this in turn leads to the text being pushed to the right and getting cutoff by the boxes.

Different splitcex and tipcex values do not affect/fix this.

**Comment by nmatzke** [comment]
On this issue -- an easier method is to put plots in a PDF of very large size -- e.g. increase the "width" and "height" options to e.g. 18 and 60 inches:

```
pdffn = "example.pdf"
pdf(file=pdffn, width=6, height=6)
[put plotting code here]
dev.off()
cmdstr = paste0("open ", pdffn)
system(cmdstr)

```

...closing the issue.
