### ISSUE TITLE
Error in BSM analysis with manual modifications of the states list

### ISSUE THREAD

**Issue by alterrones** [nmatzke/BioGeoBEARS#7]
When performing a BSM analysis with max_range_size =3 and manual modifications of the states list, I found an error "Error in if (is.na(states_list[[i]])) { : the condition has length > 1" that stopped the code. After checking the code, the error appeared with the formula get_inputs_for_stochastic_mapping_from_results_object(), when it tried to get the list of text ranges from the states_list:

https://github.com/nmatzke/BioGeoBEARS/blob/7b16e5263e91389d8e16b7bead4437d39b8be5bc/R/BioGeoBEARS_stochastic_mapping_v1.R#L2051

In my case, changing the line for the following solved the error:

if ( (length(states_list[[i]]) == 1) && (is.na(states_list[[i]])) )

However, I do not know if this is the best way to solve it, although I have seen a similar code in other functions. The error also appears in the function add_cladogenetic_events_to_trtable().

https://github.com/nmatzke/BioGeoBEARS/blob/7b16e5263e91389d8e16b7bead4437d39b8be5bc/R/BioGeoBEARS_stochastic_mapping_v1.R#L1695

**Comment by nmatzke** [comment]
Hi -- thanks! If you can email me your files & code I can double check it.  Cheers, NIck

**Comment by nmatzke** [comment]
Subsumed by later updates.

**Comment by SarahSW155** [comment]
Hi Nick, this is issue still occurs for me when trying to use get_inputs_for_stochastic_mapping_from_results_object() and run_BSM() with a manually modified states list. Even with the latest GitHub version of BioGeoBEARS.
