### ISSUE TITLE
BioGeoBEARS archived on CRAN

### ISSUE THREAD

**Issue by willgearty** [nmatzke/BioGeoBEARS#8]
It appears BioGeoBEARS is currently archived on CRAN due to [failing various checks](https://cran-archive.r-project.org/web/checks/2019/2019-01-28_check_results_BioGeoBEARS.html). Are there any plans to restore BioGeoBEARS to CRAN? We are including it in the new [phylogenetics CRAN task view](https://github.com/cran-task-views/Phylogenetics), but it'd be much better to be able to link to the CRAN version.

**Comment by nmatzke** [comment]
Hi! It lives on GitHub at: https://github.com/nmatzke/BioGeoBEARS

The accessory packages are on CRAN, as having the compiled binaries was
necessary for using the C++ and FORTRAN code:
https://cran.r-project.org/web/packages/cladoRcpp/
https://cran.r-project.org/web/packages/rexpokit/index.html

...but the actual BioGeoBEARS is just pure R which is easy to install on
any machine, and so it was easier to just update it on GitHub.  Up to you
whether this fits the CRAN task view. I do hope to get BioGeoBEARS back on
CRAN, probably as a final long-term release, but it won't happen in the
near term.

Cheers!
Nick

**Comment by willgearty** [comment]
No worries, we'll keep it included through the GitHub repo and can update it whenever you are able to get it back on CRAN.
