### ISSUE TITLE
BioGeoBEARS Suggests package kexpmv installed failed

### ISSUE THREAD

**Issue by RisenL** [nmatzke/BioGeoBEARS#9]
> pacman::p_load_gh("cran/kexpmv")

── R CMD build ──────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/yh/302gmnvs3rldbp86z2f78nx40000gn/T/RtmpDj70wV/remotes7d244f5c7854/cran-kexpmv-0ee180b/DESCRIPTION’ ...
─  preparing ‘kexpmv’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘kexpmv_0.0.3.tar.gz’
   
* installing *source* package ‘kexpmv’ ...
** using staged installation
** libs
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c blas_mod.f -o blas_mod.o
blas_mod.f:4:38:

    4 |       SUBROUTINE XERBLA ( SRNAME, INFO )
      |                                      1
Warning: Unused dummy argument 'info' at (1) [-Wunused-dummy-argument]
blas_mod.f:136:37:

  136 |       double precision dx(n),dy(n),da
      |                                     1
Warning: Unused variable 'da' declared at (1) [-Wunused-variable]
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c kexmpv_init.c -o kexmpv_init.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c lapack.f -o lapack.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c mataid.f -o mataid.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c my_expokit.f -o my_expokit.o
my_expokit.f:294:4:

  294 |  402  continue
      |    1
Warning: Label 402 at (1) defined but not used [-Wunused-label]
my_expokit.f:276:4:

  276 |  300  continue
      |    1
Warning: Label 300 at (1) defined but not used [-Wunused-label]
my_expokit.f:1011:4:

 1011 |  500  continue
      |    1
Warning: Label 500 at (1) defined but not used [-Wunused-label]
my_expokit.f:933:4:

  933 |  402  continue
      |    1
Warning: Label 402 at (1) defined but not used [-Wunused-label]
my_expokit.f:915:4:

  915 |  300  continue
      |    1
Warning: Label 300 at (1) defined but not used [-Wunused-label]
my_expokit.f:268:10:

  268 |       if ( hj1j.gt.break_tol ) then
      |          ^
Warning: 'hj1j' may be used uninitialized [-Wmaybe-uninitialized]
my_expokit.f:153:42:

  153 |      .                 vnorm, avnorm, hj1j, hij, hump, SQR1,
      |                                          ^
note: 'hj1j' was declared here
my_expokit.f:302:72:

  302 |          p2 = ABS( wsp(iexph+m+1) ) * beta * avnorm
      |                                                                        ^
Warning: 'avnorm' may be used uninitialized [-Wmaybe-uninitialized]
my_expokit.f:153:36:

  153 |      .                 vnorm, avnorm, hj1j, hij, hump, SQR1,
      |                                    ^
note: 'avnorm' was declared here
my_expokit.f:907:13:

  907 |          if ( hj1j.gt.break_tol ) then
      |             ^
Warning: 'hj1j' may be used uninitialized [-Wmaybe-uninitialized]
my_expokit.f:803:42:

  803 |      .                 vnorm, avnorm, hj1j, hij, hump, SQR1
      |                                          ^
note: 'hj1j' was declared here
my_expokit.f:941:72:

  941 |          p2 = ABS( wsp(iexph+m+1) ) * beta * avnorm
      |                                                                        ^
Warning: 'avnorm' may be used uninitialized [-Wmaybe-uninitialized]
my_expokit.f:803:36:

  803 |      .                 vnorm, avnorm, hj1j, hij, hump, SQR1
      |                                    ^
note: 'avnorm' was declared here
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c my_matexp.f -o my_matexp.o
my_matexp.f:94:5:

   94 |  9001 format( 4(1X,D11.2) )
      |     1
Warning: Label 9001 at (1) defined but not used [-Wunused-label]
my_matexp.f:95:5:

   95 |  9000 format( 4(1X,I2.1) )
      |     1
Warning: Label 9000 at (1) defined but not used [-Wunused-label]
my_matexp.f:92:15:

   92 |       integer i,j
      |               1
Warning: Unused variable 'i' declared at (1) [-Wunused-variable]
my_matexp.f:92:17:

   92 |       integer i,j
      |                 1
Warning: Unused variable 'j' declared at (1) [-Wunused-variable]
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c rcpp_module.cpp -o rcpp_module.o
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c wrappers.cpp -o wrappers.o
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o kexpmv.so blas_mod.o kexmpv_init.o lapack.o mataid.o my_expokit.o my_matexp.o rcpp_module.o wrappers.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: ignoring file lapack.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file my_matexp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file my_expokit.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file mataid.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file blas_mod.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file /usr/local/gfortran/lib/libgfortran.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /usr/local/gfortran/lib/libquadmath.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
installing to /Library/Frameworks/R.framework/Versions/4.2/Resources/library/00LOCK-kexpmv/00new/kexpmv/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘kexpmv’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/00LOCK-kexpmv/00new/kexpmv/libs/kexpmv.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/00LOCK-kexpmv/00new/kexpmv/libs/kexpmv.so, 0x0006): symbol not found in flat namespace '_mydgexpv_'
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/kexpmv’
Warning messages:
1: In i.p(...) :
  installation of package ‘/var/folders/yh/302gmnvs3rldbp86z2f78nx40000gn/T//RtmpDj70wV/file7d243fdffb80/kexpmv_0.0.3.tar.gz’ had non-zero exit status
2: In p_install_gh(package, dependencies, ...) :
  The following may have incorrect capitalization specification:

kexpmv
3: In pacman::p_load_gh("cran/kexpmv") : 
Failed to install/load:
cran/kexpmv

**Comment by nmatzke** [comment]
Whoops!  kexpmv was a CRAN package that had some modified sparse-matrix exponentiation functions. But it's been off of CRAN for some time, I am removing it from "Suggests".
